-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- Start with symbols outline window open
-- vim.api.nvim_create_autocmd("GUIEnter", {
--   group = vim.api.nvim_create_augroup("SymbolsOutlineOpen", { clear = true }),
--   callback = function()
--     command = "SymbolsOutlineOpen"
--   end,
-- })
